config/routes.rb
Capo::Application.routes.draw do

  get "pages/about"
  get "sessions/new"
  get "main/home"
    
  get "open_mics/attend"
  get "open_mics/unattend"
  get "open_mics/attendee_list"
  get "open_mics/attending_info"
  get "open_mics/selectable_cities_with_prov_state"
  match "open_mics/add_host" => "open_mics#add_host"
  match "open_mics/remove_host" => "open_mics#remove_host"
  
  get "users/show_me"
  post "users/ajax_update"

  get "sessions/signed_in"
  
  resources :users
  resources :open_mics do
    resources :posts
  end
  resources :sessions,            :only => [:new, :create, :destroy]
  resources :posts
  
  post "posts/create_site_news"
  
  root :to => 'main#home'

  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/signup', :to => 'users#new'
  match '/feedback', :to => 'pages#feedback'
  match '/about', :to => 'pages#about'
  
  match '/browsers/desktop', :to => 'browsers#desktop'
  match '/browsers/mobile', :to => 'browsers#mobile'

end

app/models/open_mic.rb
class OpenMic < ActiveRecord::Base
  attr_accessible :name, 
                  :start_time, 
                  :end_time, 
                  :street_1, 
                  :street_2, 
                  :city, 
                  :prov_state,
                  :postal_zip, 
                  :country,
                  :url,
                  :published,
                  :dow
                  
  has_and_belongs_to_many :users
  has_and_belongs_to_many :hosts, :class_name => "User", 
                          :join_table => "hosted_open_mics_hosts",
                          :foreign_key => "hosted_open_mic_id",
                          :association_foreign_key => "host_id"
  
  has_many :posts
  
  default_scope order("dow")
  scope :published, where(:published => true).order("dow")
  
  validates :name, :presence => true
  validates :dow, :presence => true
  
  def add_attendee(user)
    if !users.include?(user)
      users << user
    else
      errors.add(:users, " already contains the user.")
    end
    update
  end
  
  def remove_attendee(user)
    users.delete(user)
    update
  end
  
  def remove_all_attendees
    users.delete_all
  end
  
  def add_host(user)
    hosts << user
    update
  end
  
  def remove_host(user)
    hosts.delete(user)
    update
  end
  
  def address_blank?
    street_1.blank? &&
    street_2.blank? &&
    city.blank? &&
    prov_state.blank?    
  end
  
end

app/controllers/open_mics_controller.rb
class OpenMicsController < ApplicationController
  
  respond_to :json, :html
  
  before_filter :deny_access_for_non_admins, :only => [:edit, :destroy, :add_host, :remove_host]
  before_filter :authenticate              , :only => [:attend, :unattend]
  before_filter :split_city_and_prov_state , :only => [:index]
  
  def new
    @open_mic = OpenMic.new
    @title = "Create New Open Mic"
  end
  
  def create
    @open_mic = OpenMic.new(params[:open_mic])
    if verify_recaptcha(:model => @open_mic, :message => "Captcha entry was incorrect") && @open_mic.save
      flash[:success] = "Thank you for submitting your Open Mic. Once it is approved it will show up in list!"
      
      respond_to do |format|
        format.html { redirect_to @open_mic }
        format.json { render :json => { :response => true }.to_json }
      end
      
    else
      @title = "Create New Open Mic"
      
      respond_to do |format|
        format.html { render 'new' }
        format.json { render :json => { :response => false }.to_json }
      end
    end
  end
  
  def show
    @open_mic = OpenMic.find(params[:id])
    @gmaps_address = gmaps_address(@open_mic)
    @posts = @open_mic.posts.order(:updated_at).limit(5)
    
    @post = Post.new if can_manage_posts_for(@open_mic)
    
    respond_to do |format|
      format.html
      format.json { render :json => @open_mic.as_json(:include => :hosts) }
    end
  end
  
  def index
    @selectable_cities_with_prov_state = cities_with_prov_state
    @open_mics = OpenMic.scoped
    @open_mics = @open_mics.published unless admin?
    @open_mics = @open_mics.where(:city => @city, :prov_state => @prov_state) if @selected_city_prov_state.present?
    
    respond_to do |format|
      format.html
      format.json { render :json => @open_mics }
      format.xml {render :xml => @open_mics }
    end
  end
  
  def edit
    @open_mic = OpenMic.find(params[:id])
  end
  
  def update
    @open_mic = OpenMic.find(params[:id])
    if @open_mic.update_attributes(params[:open_mic])
      flash[:success] = "Open Mic Updated."
      redirect_to @open_mic
    else
      @title = "Edit Open Mic"
      render 'edit'
    end
  end
  
  def destroy
    OpenMic.find(params[:id]).destroy
    redirect_to open_mics_path
  end
  
    
  def add_host
    user = User.find_by_id(params[:host_to_add][:id])
    open_mic = OpenMic.find(params[:id])
    open_mic.add_host(user)
    redirect_to open_mic
  end
  
  def remove_host
    user = User.find_by_id(params[:host_to_remove])
    open_mic = OpenMic.find(params[:id])
    open_mic.remove_host(user)
    redirect_to open_mic
  end
  
  def attend

    @open_mic = OpenMic.find(params[:id])
    
    @open_mic.add_attendee(current_user)

    if @open_mic.errors.empty?
      response = {:response => true, :attendee_count => @open_mic.users.size}
    else
      error_message = "You are already attending this open mic."
      flash[:error] = error_message
      response = {:response => false, :message => error_message}
    end

    respond_with(response) do |format|
      format.html { redirect_to @open_mic }
    end
  end
  
  def unattend
    @open_mic = OpenMic.find(params[:id])
    @open_mic.remove_attendee(current_user)
    
    respond_to do |format|
      format.html { redirect_to @open_mic}
      format.json { render :json => { :response => true, :attendee_count => @open_mic.users.size }.to_json }
    end
  end
  
  def attending_info
    @open_mic = OpenMic.find(params[:id])
    count = @open_mic.users.size
    attending = @open_mic.users.include?(current_user) ? true : false
    respond_to do |format|
      format.json { render :json =>  { :attending => attending, :attendee_count => count }.to_json }
    end
  end
  
  def attendee_list
    @open_mic = OpenMic.find(params[:id])
    respond_to do |format|
      format.json { render :json => @open_mic.users.to_json }
    end
  end
  
  def selectable_cities_with_prov_state
    respond_to do |format|
      format.json { render :json => cities_with_prov_state.to_json }
    end
  end
  

  private
  
    def cities_with_prov_state
      OpenMic.unscoped.select("DISTINCT CITY, PROV_STATE").collect { |x| "#{x.city}, #{x.prov_state}" }
    end
    
    def split_city_and_prov_state
      @selected_city_prov_state = params[:filter_city_prov_state]
      @city = params[:filter_city_prov_state].split(',').first unless @selected_city_prov_state.blank?
      @prov_state = params[:filter_city_prov_state].split(',').last.strip unless @selected_city_prov_state.blank?
    end
  
    def gmaps_address(open_mic)
      if open_mic.street_1.nil? || open_mic.street_1.strip == '' ||
        open_mic.city.nil? || open_mic.city.strip == ''
        nil
      else
        ret = open_mic.street_1 + " " + open_mic.city
        if !open_mic.prov_state.nil? && open_mic.prov_state.strip != ''
          ret += ", " + open_mic.prov_state
        end
        ret
      end
        
    end

end

app/helpers/open_mics_helper.rb
module OpenMicsHelper

  def can_manage_posts_for(open_mic)
    host?(open_mic) || admin?
  end

end

app/views/open_mics/_attendees.html.erb
	<!-- Attendees -->
	<h2>Attendees</h2>
	<% if signed_in? %>
		<% if @open_mic.users.include?(current_user) %>
			<%= link_to image_tag("unattend.png"), :controller => 'open_mics', :action => 'unattend', :id => @open_mic.id, :class => 'green-button' %>
		<% else %>
			<%= link_to image_tag("attend.png"), :controller => 'open_mics', :action => 'attend', :id => @open_mic.id %>
		<% end %>
	
		<% if !@open_mic.users.empty? %>
				<ul class="attendees-list">
					<% @open_mic.users.each do |attendee| %>
						<li>
							<%= gravatar_image_tag attendee.email, :class => 'gravatar-small' %>
							<%= link_to attendee.first_name + ' ' + attendee.last_name, attendee %>
						</li>
					<% end %>
				</ul>		
		<% end %>
		<br/>
		<br/>
		Attendee List is cleared at 5:00 AM EST every week the day after the Open Mic.
	<% else %>
		<%= link_to image_tag("signin.png"), '/signin' %>
		<br/>
		<br/>
		Signin to view attendee list and attend yourself!
	<% end %>

app/views/open_mics/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>
<div class="field">
	<%= f.label :name, 'Name of Open Mic or Venue' %>
	<br />
	<%= f.text_field :name %>
</div>
<div class='field'>
	<%= f.label :dow, 'Day of the Week' %>
	<br />
	<%= f.select :dow, [['Sunday', 0], ['Monday', 1], ['Tuesday', 2], ['Wednesday', 3], ['Thursday', 4], ['Friday', 5], ['Saturday', 6]] %>
</div>
<div class="field">
	<%= f.label :start_time %> (examples '09:00' or '23:00')
	<br />
	<%= f.time_select :start_time %>
</div>
<div class="field">
	<%= f.label :end_time %> (examples: '9:00' or '23:00')
	<br />
	<%= f.time_select :end_time %>
</div>
<div class="field">
	<%= f.label :street_1 %>
	<br />
	<%= f.text_field :street_1 %>
</div>
<div class="field">
	<%= f.label :street_2 %>
	<br />
	<%= f.text_field :street_2 %>
</div>
<div class="field">
	<%= f.label :city %>
	<br />
	<%= f.text_field :city %>
</div>
<div class="field">
	<%= f.label :prov_state, 'Province/State' %>
	<br />
	<%= f.select :prov_state, options_for_select([[ "Select a Province/State", "" ]] + 
  			provinces_and_states, :selected => @open_mic.prov_state) %>
</div>
<div class="field">
	<%= f.label :postal_zip, 'Postal Code/Zip Code' %>
	<br />
	<%= f.text_field :postal_zip %>
</div>
<div class="field">
	<%= f.label :country %> (automatically populated by selecting province/state)
	<br />
	<%= f.text_field :country, :readonly => "true" %> 
</div>
<div class="field">
	<%= f.label :url, 'Official Home Page URL' %>
	<br />
	<%= f.text_field :url %>
</div>
<div class="field">
	<%= recaptcha_tags :display => { :theme => "clean" } %>
</div>

<script type="text/javascript">
	$("#open_mic_prov_state").change(function(){
		if( ($("#open_mic_prov_state").val() == "AB") ||
			($("#open_mic_prov_state").val() == "BC") ||
			($("#open_mic_prov_state").val() == "MB") ||
			($("#open_mic_prov_state").val() == "NB") ||
			($("#open_mic_prov_state").val() == "NL") ||
			($("#open_mic_prov_state").val() == "NT") ||
			($("#open_mic_prov_state").val() == "NS") ||
			($("#open_mic_prov_state").val() == "NU") ||
			($("#open_mic_prov_state").val() == "ON") ||
			($("#open_mic_prov_state").val() == "QC") ||
			($("#open_mic_prov_state").val() == "SK") ||
			($("#open_mic_prov_state").val() == "PE") ||
			($("#open_mic_prov_state").val() == "YT")) {
			$("#open_mic_country").val("Canada");		
		}
		else {
			$("#open_mic_country").val("United States");
		}
	});
</script>

app/views/open_mics/_info.html.erb
<!-- General info -->
	<h2>General Info</h2>
	<div class="infosection">
		<table class="generalinfo">
			<tr>
				<td>
					<!-- Date and Time -->
					<h2>When</h2>
					<%= Date::DAYNAMES[@open_mic.dow].pluralize() %><br/>
					<% if !@open_mic.start_time.nil? %>
						Start Time: <%= @open_mic.start_time.strftime("%I:%M%p") %><br/>
					<% end %>
					<% if !@open_mic.end_time.nil? %>
						End Time: <%= @open_mic.end_time.strftime("%I:%M%p") %>
					<% end %>

					<% if !@open_mic.url.nil? && @open_mic.url.strip != "" %>
						<p>
							<h2>Official Home Page</h2>	
							<%= link_to @open_mic.url, @open_mic.url, :target => "_blank" %>
						</p>
					<% end %>


					<!-- Hosts -->
					<% if !@open_mic.hosts.empty? %>
						<h2>Host
				
							<% if host?(@open_mic) %>
				 				| <i>You are a host of this Open Mic!</i>
							<% end %>
						</h2>
						<% @open_mic.hosts.each do |host| %>
							<%= host.full_name %>
							<% if admin? %>
								| <%= link_to "remove", :controller => "open_mics", :action => "remove_host", :method => :post, :host_to_remove => host, :id => @open_mic %>
							<% end %>
							<br/>
						<% end %>
		

					<% end %>

					<% if admin? %>
						<%= form_tag("/open_mics/add_host", :method => "post") do %>
  							<%= label_tag(:host_to_add, "Add Host:") %>
  							<%= collection_select :host_to_add, :id, User.all, :id, :full_name %>
  							<%= hidden_field_tag(:id, @open_mic.id)%>
  							<%= submit_tag("Add") %>
						<% end %>
					<% end %>

					<!-- Address and Contact -->
					<% if !@open_mic.address_blank? %>
						<h2>Address</h2>
						<%= @open_mic.street_1 %><br/>
						<% unless @open_mic.street_2.blank? %>
							<%= @open_mic.street_2 %><br/>
						<% end %>
						<%= @open_mic.city %><br/>
						<%= @open_mic.prov_state %><br/>
						<% unless @open_mic.postal_zip.blank? %>
							<%= @open_mic.postal_zip %><br/>
						<% end %>
						<%= @open_mic.country %><br/>
					<% end %>
				</td>
			
				<!-- Load Google Map -->
				<% if !@gmaps_address.nil? %>
					<td class='map'>
						<div class="map_container">				
							<div id="map_canvas"></div>
						</div>
					</td>
			
				  
  					<!-- Google Maps Javascript API -->
  					<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyAobCjmE-CweLXzArO1JL-Ogn2LjGGStAs&sensor=false">
					</script>
			
					<script type="text/javascript">
			
						/* Initialize Map */									
    					var latlng = new google.maps.LatLng(-34.397, 150.644);
    					var myOptions = {
      						zoom: 15,
      						center: latlng,
      						mapTypeId: google.maps.MapTypeId.ROADMAP
    					};
   						var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
				
						/* Geocode Address */
						geocoder = new google.maps.Geocoder();
						geocoder.geocode( { 'address': '<%= @gmaps_address %>'}, function(results, status) {
      						if (status == google.maps.GeocoderStatus.OK) {
        						map.setCenter(results[0].geometry.location);
       							var marker = new google.maps.Marker({
           							map: map, 
           							position: results[0].geometry.location
        						});
      						} 
    					});
					

  					</script>
				<% end %>	
			
			</tr>
		</table>
	</div>

app/views/open_mics/_news.html.erb
	<!-- News -->
	<h2>News</h2>
	<div class="infosection">
		<% if @posts.empty? %>
			<li> There is currently no news for this Open Mic.</li>
		<% else %>
			<% @posts.each do |post| %>
				<li><%= post.updated_at.strftime("%B %d, %Y: ") + " " + post.body %></li>
			<% end %>
		<% end %>
	</div>
	<%= link_to "View All News", open_mic_posts_url(@open_mic) %>

	<br/><br/>

	<% if can_manage_posts_for(@open_mic) %>
		<p>
			<%= form_for [@open_mic, @post] do |f| %>
  				<%= render 'shared/error_messages', :object => f.object %>
  				<div class="field">
   		 			<%= f.text_area :body, :class => "post", :placeholder => "You are the host of this open mic! Feel free to post some news here!" %>		
    			</div>
 				<%= f.hidden_field :open_mic_id, :value => @open_mic.id %>
  				<div class="actions">
    				<%= f.submit "Publish News" %>
  				</div>
			<% end %>
		</p>
	<% end %>

app/views/open_mics/edit.html.erb
<h1>Edit New Open Mic</h1>

<%= form_for(@open_mic) do |f| %>
	<%= render 'fields', :f => f %>
	
	<div class="field">
		<%= f.label :published %>
		<br />
		<%= f.check_box :published %>
	</div>
	
	<div class="actions">
		<%= f.submit "Update" %>
	</div>
	
<% end %>

app/views/open_mics/index.html.erb
<!-- This is not scalable. Need to generate lists by DOW in Controller with one loop pass -->
<div class='location-filter'>
	<%= form_tag({:controller => "open_mics", :action => "index"}, :method => "get", :class => "float-left") do %>
	
  		<%= label_tag "Filter by City" %>: 
  		
  		<%= select_tag :filter_city_prov_state, 
  			options_for_select(
  				@selectable_cities_with_prov_state,
  				:selected => @selected_city_prov_state) %>
		<%= submit_tag "Submit" %>
		
	<% end %>
	<%= form_tag("/open_mics", :method => "get") do %>
		<%= hidden_field_tag :filter_city %>
		<%= submit_tag "Clear" %>
	<% end %>
</div>
<ul class="open-mic-list">
	<% (0..6).each do |i| %>
		<h2><%= Date::DAYNAMES[i].downcase %></h2>
		<% @open_mics.each do |open_mic| %>
			<% if open_mic.dow == i %>
				<li>
					<%= link_to open_mic.name + " | " + open_mic.city + ", " + open_mic.prov_state, open_mic %>
					<% if !open_mic.published %>
						not published
					<% end %>
				</li>
			<% end %>	
		<% end %>
	<% end %>
</ul>

app/views/open_mics/new.html.erb
<h1>Submit a New Open Mic</h1>
<h2>Fill out what you know and leave the rest blank.</h2>
<%= form_for(@open_mic) do |f| %>
	<%= render 'fields', :f => f %>
	<div class="actions">
		<%= f.submit "Submit" %>
	</div>
<% end %>

app/views/open_mics/show.html.erb
<% if @open_mic.published %>
	<table class='full-width' >
		<tr>
			<td>
				<h1>
					<%= @open_mic.name %>
					<% if admin? %>
						| <%= link_to "edit", edit_open_mic_path(@open_mic) %>
						| <%= link_to 'delete', @open_mic, 
								:method => :delete, 
								:confirm => "Are you sure you want to delete #{@open_mic.name}?", 
								:title => "Delete Open Mic?" %>
					<% end %>
				</h1>

				<%= render 'news' %>
				<%= render 'info' %>
			</td>
			<td class='attendees-column'>
				<%= render 'attendees' %>				
			</td>
		</tr>
	</table>
	
<% else %>
	<h1>Open Mic Coming Soon!</h1>
	<p>This page contains Open Mic Information that is awaiting approval.</p>
	<% if admin? %>
		<%= link_to "publish", edit_open_mic_path(@open_mic) %> 
		| <%= link_to 'delete', @open_mic, 
						:method => :delete, 
						:confirm => "Are you sure you want to delete #{@open_mic.name}?", 
						:title => "Delete Open Mic?" %>
	<% end %>
<% end%>