config/routes.rb
Capo::Application.routes.draw do

  get "pages/about"
  get "sessions/new"
  get "main/home"
    
  get "open_mics/attend"
  get "open_mics/unattend"
  get "open_mics/attendee_list"
  get "open_mics/attending_info"
  get "open_mics/selectable_cities_with_prov_state"
  match "open_mics/add_host" => "open_mics#add_host"
  match "open_mics/remove_host" => "open_mics#remove_host"
  
  get "users/show_me"
  post "users/ajax_update"

  get "sessions/signed_in"
  
  resources :users
  resources :open_mics do
    resources :posts
  end
  resources :sessions,            :only => [:new, :create, :destroy]
  resources :posts
  
  post "posts/create_site_news"
  
  root :to => 'main#home'

  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/signup', :to => 'users#new'
  match '/feedback', :to => 'pages#feedback'
  match '/about', :to => 'pages#about'
  
  match '/browsers/desktop', :to => 'browsers#desktop'
  match '/browsers/mobile', :to => 'browsers#mobile'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body
  
  belongs_to :open_mic
  belongs_to :user

  default_scope order("updated_at desc")
  scope :site_news, where(:open_mic_id => nil)  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_filter :load_open_mic, :except => [:create_site_news]
  before_filter :except => [:index, :create_site_news] do |controller|
    deny_access_for_non_hosts(@open_mic)
  end
  before_filter :only => [:create_site_news] do |controller|
    deny_access_for_non_admins
  end
  
  def create
    @post  = @open_mic.posts.build(params[:post])
    @post.user = current_user    
        
    if @post.save
      flash[:success] = "Posted!"
    end

    redirect_to @open_mic
  end

  def index
  end
  
  def destroy
    @post = Post.find(params[:id])    
    @post.destroy
    redirect_to open_mic_posts_url(@open_mic)
  end
  
  def create_site_news
    @post = Post.new(params[:post])
    @post.user = current_user
    if @post.save
      flash[:success] = "Posted!"
    else
      flash[:success] = "Could not post news!"
    end
    redirect_to root_path
  end
  
  private
    def load_open_mic
      @open_mic = OpenMic.find(params[:open_mic_id])
    end
    
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<h1>All News for <%= @open_mic.name %></h1>

<ul>
	<% if @open_mic.posts.empty? %>
		<li> There is currently no news for this Open Mic.</li>
	<% else %>
		<% @open_mic.posts.each do |post| %>
			<li>
				<%= post.updated_at.strftime("%B %d, %Y: ") + " " + post.body %> 
				<% if can_manage_posts_for(@open_mic) %>
					| <%= link_to "delete", open_mic_post_path(@open_mic, post), 
								:method => :delete, 
								:confirm => "Are you sure you want to delete #{post.body}?", 
								:title => "Delete Post?" %>
				<% end %>
			</li>
		<% end %>
	<% end %>
</ul>


<%= link_to "Back", @open_mic %>