config/routes.rb
Capo::Application.routes.draw do

  get "pages/about"
  get "sessions/new"
  get "main/home"
    
  get "open_mics/attend"
  get "open_mics/unattend"
  get "open_mics/attendee_list"
  get "open_mics/attending_info"
  get "open_mics/selectable_cities_with_prov_state"
  match "open_mics/add_host" => "open_mics#add_host"
  match "open_mics/remove_host" => "open_mics#remove_host"
  
  get "users/show_me"
  post "users/ajax_update"

  get "sessions/signed_in"
  
  resources :users
  resources :open_mics do
    resources :posts
  end
  resources :sessions,            :only => [:new, :create, :destroy]
  resources :posts
  
  post "posts/create_site_news"
  
  root :to => 'main#home'

  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/signup', :to => 'users#new'
  match '/feedback', :to => 'pages#feedback'
  match '/about', :to => 'pages#about'
  
  match '/browsers/desktop', :to => 'browsers#desktop'
  match '/browsers/mobile', :to => 'browsers#mobile'

end

app/views/layouts/_header.html.erb
<% unless @hideheader%>
<header>
	<%= link_to logo, root_path %>
	<nav class="round">
		<ul>
			<li>
				<%= link_to "Home", root_path %>
			</li>
			<li>
				<%= link_to "Browse", "/open_mics" %>
			</li>
			<li>
				<%= link_to "Submit Open Mic", :controller => "open_mics", :action => "new" %>
			</li>
			<li>
				<%= link_to "Feedback", "/feedback" %>
			</li>
			<li>
				<%= link_to "About", "/about" %>
			</li>
			<% if signed_in? %>
				<% if admin? %>
					
					<li>
						<%= link_to "Users", users_path %>
					</li>
				<% end %>
				<li>
					<%= link_to 'Profile', current_user %>
				</li>
				<li>
					<%= link_to "Sign out", signout_path %>
				</li>
			<% else %>
				<li>
					<%= link_to "Sign in", signin_path %>
				</li>
			<% end %>
		</ul>
	</nav>
</header>
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  	<title>Capo</title>
  	<%= stylesheet_link_tag 'main' %>
  	<%= stylesheet_link_tag 'easySlider' %>
  	
  	<%= javascript_include_tag 'prototype.js', 'effects.js', 'dragdrop.js', 'controls.js', 'application.js' %>
  	<%= javascript_include_tag 'jquery-1.7.min.js'%>
  	<%= javascript_include_tag 'rails.js'%>
  	<%= javascript_include_tag 'easySlider1.5.js' %>
  	<%= csrf_meta_tag %>  
  	
  	<!--[if lt IE 9]>
		<script>
			document.createElement('header');
			document.createElement('nav');
			document.createElement('section');
			document.createElement('article');
			document.createElement('aside');
			document.createElement('footer');
			document.createElement('hgroup');
		</script>
	<![endif]-->
		
	<!-- Google Analytics -->
	<script type="text/javascript">

  		var _gaq = _gaq || [];
  		_gaq.push(['_setAccount', 'UA-28912916-1']);
  		_gaq.push(['_trackPageview']);

  		(function() {
    		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  		})();

	</script>
	
	<!-- Google +1 -->
	<script type="text/javascript">
  		(function() {
    		var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    		po.src = 'https://apis.google.com/js/plusone.js';
    		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  	})();
</script>
		
</head>
<body>
	<!-- Facebook Like -->
	<div id="fb-root"></div>
	<script>
		(function(d, s, id) {
  			var js, fjs = d.getElementsByTagName(s)[0];
  			if (d.getElementById(id)) return;
  			js = d.createElement(s); js.id = id;
  			js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  			fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));
	</script>
	
	<div class="header">
		<div class="header-container">
			<%= render 'layouts/header'%>
		</div>
	</div>
	
	<div class="container">
			<% flash.each do |key, value| %>
				<div class="flash <%= key %>"><%= value %></div>
			<% end %>
		<div class="main">
			<%= yield %>
		</div>
		<div class="footer">
			<%= render 'layouts/footer' %>
		</div>
	</div>
</body>
</html>

app/views/layouts/application.iphone.erb
<html>
    <head>
        <title>Capo</title>
        
        <!-- JQTouch -->
        <%= stylesheet_link_tag "iphone" %>
        <link type="text/css" rel="stylesheet" media="screen" href="jqtouch/jqtouch.css">
		<link type="text/css" rel="stylesheet" media="screen" href="themes/capo/theme.css">
		<link type="text/css" rel="stylesheet" media="screen" href="jquery-loadmask-capo/jquery.loadmask.capo.css">
		<script type="text/javascript" src="jqtouch/jquery-1.4.2.js"></script>
		<script type="text/javascript" src="jqtouch/jqtouch.js"></script>
		<script type="text/javascript" src="jquery-loadmask-capo/jquery.loadmask.capo.js"></script>
		<%= javascript_include_tag 'jquery.gravatar' %>
		<%= javascript_include_tag 'md5' %>
		<script type="text/javascript">
    		var jQT = $.jQTouch({
        		icon: 'apple-touch-icon-114x114.png',
        		statusBar: 'black',
        		addGlossToIcon: false,
        		startupScreen: '/images/iphonestartup.png'
    		});
    	</script>
    	<%= render "iphone/eventhandlers" %>
    	<%= render 'iphone/initialize' %>
    </head>
    <body onload="initialize()">
    	<%= render "iphone/ui" %>  
    </body>
</html>